# -*- coding: utf-8 -*-
"""2502190039_lab04_jobA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LogyQA2qSoByNmMzwL79hWEuL-uOA1ce
"""

import random

LIMIT_LO = 24.95
LIMIT_HI = 25.05

accepted = 0
rejected = 0

for part in range(200):

    dia = round(random.uniform(24.85, 25.15), 3)

    if LIMIT_LO <= dia <= LIMIT_HI:
        accepted += 1
        print("Part", part + 1, ":", dia, "ACCEPT ✓")
    else:
        rejected += 1
        print("Part", part + 1, ":", dia, "REJECT ✗")

print("\nShift report:")
print(accepted, "accepted,", rejected, "rejected")