# -*- coding: utf-8 -*-
"""2502190039.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LogyQA2qSoByNmMzwL79hWEuL-uOA1ce
"""

import random
import datetime
import math

# -------------------------------
# INITIALIZATION
# -------------------------------

accepted = 0
rejected = 0
consecutive_rejects = 0
alarms = 0
first_alarm_part = None

# Tolerance limits
lower_limit = 24.90
upper_limit = 25.10

# -------------------------------
# JOB A + JOB B
# -------------------------------

for part in range(1, 201):

    # Normal machine variation
    if part <= 100:
        dia = round(random.uniform(24.85, 25.15), 3)

    # Tool wear after part 100
    else:
        dia = round(random.uniform(24.90, 25.20), 3)

    # ---------------------------
    # QUALITY CHECK
    # ---------------------------

    if lower_limit <= dia <= upper_limit:
        print(f"Part {part}: {dia} mm -> ACCEPT")

        accepted += 1
        consecutive_rejects = 0

    else:
        print(f"Part {part}: {dia} mm -> REJECT")

        rejected += 1
        consecutive_rejects += 1

    # ---------------------------
    # TOOL WEAR ALARM
    # ---------------------------

    if consecutive_rejects == 3:
        print(f"⚠ TOOL WEAR SUSPECTED at part {part}")

        alarms += 1

        if first_alarm_part is None:
            first_alarm_part = part


# -------------------------------
# JOB C : SHIFT REPORT
# -------------------------------

now = datetime.datetime.now()

print("\n" + "=" * 45)
print("SHIFT REPORT ·", now.strftime("%d-%m-%Y %H:%M"))
print("=" * 45)

print("Operators    : Ayushi Srivastava, Shreeya Routray")
print("Parts        :", 200)

print("Accepted     :", accepted)
print("Rejected     :", rejected)

print("Acceptance   :", round(accepted / 200 * 100, 1), "%")

print("Tolerance    :", f"{lower_limit} mm - {upper_limit} mm")

print("Alarm count  :", alarms)

if first_alarm_part is not None:
    print("First alarm  : Part", first_alarm_part)
else:
    print("First alarm  : None")

print("Nominal area :", round(math.pi * (25.0 / 2) ** 2, 2), "mm2")

print("=" * 45)