# -*- coding: utf-8 -*-
"""2502190039_lab04_jobB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LogyQA2qSoByNmMzwL79hWEuL-uOA1ce
"""

import random

LIMIT_LO = 24.95
LIMIT_HI = 25.05

accepted = 0
rejected = 0

consecutive_rejects = 0
alarms = 0
first_alarm_part = None

for part in range(1, 201):

    # Normal variation for first 100 parts
    if part <= 100:
        dia = round(random.uniform(24.85, 25.15), 3)

    # Tool wear after part 100
    else:
        dia = round(random.uniform(24.90, 25.20), 3)

    if LIMIT_LO <= dia <= LIMIT_HI:

        accepted += 1
        consecutive_rejects = 0

        print("Part", part, ":", dia, "ACCEPT ✓")

    else:

        rejected += 1
        consecutive_rejects += 1

        print("Part", part, ":", dia, "REJECT ✗")

    # Tool-wear alarm
    if consecutive_rejects == 3:

        print("⚠ TOOL WEAR SUSPECTED at part", part)

        alarms += 1

        if first_alarm_part is None:
            first_alarm_part = part

print("\nShift report:")
print("Accepted:", accepted)
print("Rejected:", rejected)
print("Acceptance:", round(accepted / 200 * 100, 1), "%")
print("Alarms:", alarms)
print("First alarm:", first_alarm_part)