# -*- coding: utf-8 -*-
"""libraries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vply0h_ShqKnmeTbiOzIyQBDKdgwTOLC
"""

import numpy as np

marks = np.array([75, 82, 68, 90, 85])

print("Marks:", marks)
print("Mean:", np.mean(marks))
print("Maximum:", np.max(marks))
print("Minimum:", np.min(marks))
print("Standard Deviation:", np.std(marks))

import pandas as pd

data = {
    "Name": ["Ayushi", "Rahul", "Priya", "Aman"],
    "Marks": [85, 78, 92, 70],
    "Age": [20, 21, 20, 22]
}

df = pd.DataFrame(data)

print(df)
print("\nAverage Marks:", df["Marks"].mean())
print("\nStudents with marks above 80:")
print(df[df["Marks"] > 80])

import matplotlib.pyplot as plt

days = [1, 2, 3, 4, 5]
temperature = [30, 32, 31, 35, 34]

plt.plot(days, temperature, marker="o")
plt.xlabel("Day")
plt.ylabel("Temperature")
plt.title("Temperature vs Day")
plt.show()

from scipy import stats

marks = [75, 82, 68, 90, 85, 78, 92]

mean = stats.tmean(marks)
median = stats.scoreatpercentile(marks, 50)
mode = stats.mode(marks)

print("Mean:", mean)
print("Median:", median)
print("Mode:", mode.mode)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

marks = np.array([75, 82, 68, 90, 85, 78, 92, 88])

df = pd.DataFrame({"Marks": marks})

print(df)
print("\nMean:", np.mean(marks))
print("Maximum:", np.max(marks))
print("Minimum:", np.min(marks))
print("Standard Deviation:", np.std(marks))

print("\nDescriptive Statistics:")
print(stats.describe(marks))

plt.hist(marks, bins=5)
plt.xlabel("Marks")
plt.ylabel("Number of Students")
plt.title("Distribution of Marks")
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

# Sensor readings
time = np.array([0, 1, 2, 3, 4, 5, 6, 7])

temperature = np.array([30, 32, 35, 39, 45, 52, 65, 78])
smoke = np.array([10, 12, 15, 20, 30, 45, 65, 80])
distance = np.array([100, 95, 80, 65, 50, 35, 25, 15])
flame = np.array([0, 0, 0, 0, 1, 1, 1, 1])

# Create DataFrame
data = pd.DataFrame({
    "Time": time,
    "Temperature": temperature,
    "Smoke": smoke,
    "Distance": distance,
    "Flame": flame
})

print(data)

# Calculate normalized risk values
temp_risk = np.clip((temperature - 30) / 50, 0, 1)
smoke_risk = np.clip(smoke / 100, 0, 1)
distance_risk = np.clip((100 - distance) / 100, 0, 1)

# Overall fire risk
fire_risk = (
    0.4 * temp_risk +
    0.3 * smoke_risk +
    0.2 * distance_risk +
    0.1 * flame
)

data["Fire_Risk"] = fire_risk

# Robot decision
def robot_decision(risk):

    if risk >= 0.75:
        return "EXTINGUISH FIRE"

    elif risk >= 0.50:
        return "APPROACH FIRE"

    elif risk >= 0.25:
        return "SEARCH AREA"

    else:
        return "MOVE / SAFE"

data["Robot_Action"] = data["Fire_Risk"].apply(robot_decision)

print("\nRobot Decisions:")
print(data[["Time", "Fire_Risk", "Robot_Action"]])

# Statistical analysis
print("\nSensor Statistics:")
print(stats.describe(temperature))

# Plot temperature
plt.figure()

plt.plot(time, temperature, marker="o")

plt.xlabel("Time")
plt.ylabel("Temperature (°C)")
plt.title("Temperature Variation")

plt.grid()
plt.show()

# Plot fire risk
plt.figure()

plt.plot(time, fire_risk, marker="o")

plt.axhline(0.75, linestyle="--")
plt.axhline(0.50, linestyle="--")

plt.xlabel("Time")
plt.ylabel("Fire Risk")
plt.title("Fire Risk Analysis")

plt.grid()
plt.show()